### ISSUE TITLE
How to properly use the ttf font file?

### ISSUE THREAD

**Issue by SomewhereDave** [andrewgioia/keyrune#174]
Hey,

I have the kreyrune.ttf installed locally, but copying from the cheat sheet into a document with Keyrune selected only creates squares.  The same is true for the example doc. The preview in the fonts section represents the symbols just fine.
Am I doing something wrong?

Best regards
David

**Comment by Nantuko** [comment]
I do not know if this help - as I am also looking for a solution to this : the Cheatsheet is working up to Commander Legents . 
For the new versions ( KHM , TSR , STX, MH2,AFR,MID,VOW , VOC , MIC , AFC,KHC,C21 ) even if the icons and the codes are in Cheatsheet , it looks like they are not in the Keyrune.ttf yet .

**Comment by andrewgioia** [comment]
Hm it's possible I didn't update the font file then with the new version and it wasn't installing correctly. Could you try removing it from your system and reinstalling the latest .ttf?

**Comment by wahooka2** [comment]
I ran into the same issue with the font file (ttf) not showing "new" icons after install.  The last installed ttf was from May-2022.  Uninstalling the font from Windows and re-installing the newest worked.  If it helps, I noticed that there were actually two "Keyrune" fonts installed on my machine, both of which I removed prior to the re-install.
I think all of these are the same issue: 174, 179, 199.

**Comment by MrTeferi** [comment]
Yes #179 #199 and this issue can be closed. These are just quirks of installing a new font over previous. Usually installing over previous works fine but for whatever reason sometimes windows doesn't wish to do so, I think I've noticed this happen if you have an app currently running which is using the font such as Photoshop or code editor displaying the font contextually etc

If you ever run into this issue, just open font settings in Windows and uninstall **all** copies of Keyrune from windows, then install latest fresh. And for good measure, restart Windows as well (probably not necessary but can't hurt)

Maintainers please close these 3 issues because we have plenty of real posts that need attention and review :)
