### ISSUE TITLE
Various special chars (newer ones ) are looks like missing from Keyrune.ttf - compatibility issue ?

### ISSUE THREAD

**Issue by Nantuko** [andrewgioia/keyrune#179]
The Cheatsheet is working up to Commander Legents . All the versions from January 2021 are not working in e.g Word , Excel .
For the new versions ( KHM , TSR , STX, MH2,AFR,MID,VOW , VOC , MIC , AFC,KHC,C21 ) even if the icons and the codes are in Cheatsheet , it looks like they are not in the **Keyrune.ttf** yet , so is not possible to import set symbols in doc's .
Can you let me know if is something I can do myself , or its needed to be done by you ?

**Comment by Nantuko** [comment]
After doing some investigation the issue is only exist if you are using the fonts in LibreOffice & OpenOffice . I tried in Word/Excel 2016 and works as expected . So I can bypass the issue for now . Also this means that the symbols are all in ttf , but there is apparently a compatibility issue with LibreOffice & OpenOffice .

**Comment by wahooka2** [comment]
I ran into the same issue with the font file (ttf) not showing "new" icons after install.  The last installed ttf was from May-2022.  Uninstalling the font from Windows and re-installing the newest worked.  If it helps, I noticed that there were actually two "Keyrune" fonts installed on my machine, both of which I removed prior to the re-install.
I think all of these are the same issue: 174, 179, 199.

**Comment by MrTeferi** [comment]
Yes #174 #199 and this issue can be closed. These are just quirks of installing a new font over previous. Usually installing over previous works fine but for whatever reason sometimes windows doesn't wish to do so, I think I've noticed this happen if you have an app currently running which is using the font such as Photoshop or code editor displaying the font contextually etc

If you ever run into this issue, just open font settings in Windows and uninstall **all** copies of Keyrune from windows, then install latest fresh. And for good measure, restart Windows as well (probably not necessary but can't hurt)

Maintainers please close these 3 issues because we have plenty of real posts that need attention and review :)
