### ISSUE TITLE
[Question] How to handle icons that use x infront of the set code?

### ISSUE THREAD

**Issue by icobg123** [andrewgioia/keyrune#245]
Hi,

I'm experiencing an issue with some of sets that use `x` infront of the set code. The set code for Renaissance is `ren` in MTGJSON, but in order to display the icon correctly, I need to use the class `ss-xren` instead.

Is there a recommended way to resolve this discrepancy, or would it be possible to update the library to support the `ren` set code directly for the Renaissance icon?

Thanks in advance for your help!

**Comment by andrewgioia** [comment]
Sorry for the delayed response @icobg123. We use `x` as a class prefix whenever the set code is not an official one recognized by WotC. The issue is if it’s not official there’s nothing stopping WotC from creating a future set with that set code and causing a problem for us.

I didn’t realize MTGJson used `ren` for it, I’ll take anlook today and see if it is in fact official and update the aliases.

**Comment by andrewgioia** [comment]
Wizards doesn't list Renaissance of Rinascimento in Gatherer, but since MTGJSON and Scryfall both went with REN and RIN I think we can do the same.

**Comment by andrewgioia** [comment]
This is finally added/changed in 3.16.1
