### ISSUE TITLE
Follow up on set codes.

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#32]
Two sets are a bit problematic: Nemesis and Portal 2.
Nemesis has two commonly used set codes: NMS and NEM (I think we found more evidence for NEM being the correct code, but NMS is used as well).
For Portal 2 you have PO2 and P02 (here is the main problem if the thing in the middle is an o or a 0).

**Comment by andrewgioia** [comment]
@yandere-sliver thanks for the note, I took a look and didn't see anywhere `p02` was listed (with the zero instead of the letter). Could you let me know where you saw that?

[MTG JSON](http://mtgjson.com) uses NMS as the Nemesis set code, as does [Wikipedia](https://en.wikipedia.org/wiki/Masques_block#Nemesis). This is the one we use in Keyrune but I don't have an issue adding an alias for NEM if you've found significant usage for it.

**Comment by csuhta** [comment]
The set code for Nemesis is `NEM`, see this article: http://magic.wizards.com/en/articles/archive/ask-wizards-august-2004-2004-08-02

**Comment by yandere-sliver** [comment]
In the article csuhta listed the set code for Portal Second Age is p02. It is also one of the sources we use on the wiki for the set codes.

**Comment by andrewgioia** [comment]
Thanks guys, it's corrected now (P02 and NEM are the official ones now used in Keyrune, though I left aliases for PO2 and NMS).
