### ISSUE TITLE
How long does the CDN takes to update?

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#37]
When I go under //cdn.jsdelivr.net/keyrune/latest/ and look for the files, I find that W17 is still missing there. So how long does it take to update? It would be nice to have a benchmark, so that I know when I should update the css of the wiki.

**Comment by andrewgioia** [comment]
It looks like there was a failure on the 2.2.3 update because I switched to the correct file structure (instead of the flat files): https://github.com/jsdelivr/jsdelivr/pull/17625

I'll try to correct this today but it will need to be manually approved by them.

**Comment by andrewgioia** [comment]
@yandere-sliver this should be all set now. Version 2.2.3 is live and jsdelivr now has our correct file structure so you can point directly to http://cdn.jsdelivr.net/keyrune/latest/css/keyrune.css for instance (rather than everything being in the root directory incorrectly).

As a benchmark, it should generally be within 30 minutes that I push a new version up and jsdelivr's automerge bot merges it into the CDN. There won't be any file structure changes going forward now so we shouldn't have this issue either.
