### ISSUE TITLE
Updates v3.0.2 and v3.0.3 did not appear in CDS.

### ISSUE THREAD

**Issue by yandere-sliver** [andrewgioia/Keyrune#48]
http://cdn.jsdelivr.net/keyrune/latest still displays version 3.0.1.

I tired moving to http://cdn.jsdelivr.net/keyrune/3.0.2 and http://cdn.jsdelivr.net/keyrune/3.0.3, but both folders do not seem to exist.

Not quite sure what is up with that.

**Comment by cybey** [comment]
Having the same issue. The Archenemy: Nicol Bolas icon is not showing up.
Tried refreshing and bypassing the cache, but /latest is not updated.

**Comment by andrewgioia** [comment]
@yandere-sliver @cybey It looks like jsDelivr changed the way they're handling updates since early May. I should've been more on top of it but updates since then follow a new url structure apparently (I'm going to update the docs and readme to reflect this).

Now the new jsDelivr endpoint looks like:

    http://cdn.jsdelivr.net/npm/keyrune@latest/css/keyrune.min.css

You can specify specific releases by replacing `latest` with the version number, so `keyrune@3.1.1` for instance. I just checked and the new v3.1.1 is now hosted correctly but if you guys want to independently verify at some point I'd appreciate it.

**Comment by yandere-sliver** [comment]
New link works perfectly.
