### ISSUE TITLE
M19 symbol doesn't match actual glyph

### ISSUE THREAD

**Issue by harryfino** [andrewgioia/Keyrune#88]
The M19 set symbol in the font does not match the actual glyph on the card. Also, when you turn on `ss-grad`, it make the differences even worse. At smaller font sizes, it's almost impossible to work out what set it is. (I believe this applies to all core sets from M10 - M19)

<img width="615" alt="screen shot 2018-12-27 at 11 28 27 pm" src="https://user-images.githubusercontent.com/1643512/50502755-b81a9000-0a2f-11e9-8851-8ab2cd3d0265.png">

I don't see a way to replicate the actual glyph. Even if I made the `background-color` black, it would still not be exactly like the glyph.

<img width="816" alt="screen shot 2018-12-27 at 11 36 39 pm" src="https://user-images.githubusercontent.com/1643512/50502819-48f16b80-0a30-11e9-943d-4654a651bc96.png">

Is there any way to get this close in CSS or is there anything that can be fixed in the font?

**Comment by andrewgioia** [comment]
@harryfino thanks for the help here. For the glyph itself, adding that outer border was a design decision to replicate the existing black border on the card core set symbols. There's no way to create that in an SVG without something bounding it, it would just be empty space. We could do it via CSS and that's definitely an option as potential alternate symbols for these core sets.

Regarding the poor gradient styles, I agree they're not ideal currently. If you have any suggestions on how to make them better by all means submit a PR I would love to see it. They're more of fun/convenience classes right now that have not been checked against every symbol, though creating exceptions for the individual symbols (like M19) that show up poorly is the goal. 

I'm going to mark this as closed but these 2 are absolutely on my radar when I get more time (or if someone wants to help).

**Comment by ChristianIvicevic** [comment]
The mentioned issue is still a thing, 3 years after it has been reported. Is there any proposed workaround to have the background be black instead of white? Compare the M19 on the real card in OPs images with the Mythic rarity (non-gradient) logo I use at the moment. They don't look alike at all. The same holds true for pretty much all set icons that are of a rarity higher than common as their background color is in theory black and no longer white.

![Screenshot 2022-04-15 at 15 02 56](https://user-images.githubusercontent.com/45569997/163573931-eecd9ae3-9c99-4fd5-91d5-40330511fb34.png)

**Comment by andrewgioia** [comment]
@ChristianIvicevic If you have a PR to submit, revised glyphs you can attach, an updated way to handle these border cases in CSS only, or even an example to reference, then any of these would be 1000x more helpful than a complaint on a closed issue in a FOSS project. 

The problem is as always one of time and priorities. To upgrade M19-M21 to use the new dual-layered glyph handling and properly represent the printed card symbols would require volunteer time and prioritization. This is on the radar, as is correcting other recent symbols where WOTC decided to draw set symbols this way. If you want to speed it up then by all means do it and submit the very welcome PR, or fork the project to better meet your needs or the needs of the community.

**Comment by ChristianIvicevic** [comment]
I merely encountered the issue and only wanted to know if there is any known solution to get closer to the original look and this issue seemed to be the correct spot to note that I've just ran into it. Nothing else.

> then any of these would be 1000x more helpful than a complaint on a closed issue in a FOSS project
It is unclear why you perceive my question as an act of aggression that must be remedied with an uncouth response boiling down to "do it yourself and/or just contribute to the project".
